// -Konsgn 

/*
 * MKL27 Pin Assignments Map {name,delault mux,ALT0,ALT1..ALT7} 
 *  This is a reference to the global mapping based on pin assignment chart
 */
 
/*
{
  //NAME	DEFAULT	ALT0					ALT1					ALT2					ALT3					ALT4					ALT5					ALT6					ALT7
  // Page 28
  { PTE17, 	0, 		ADC0_DM1_ADC0_SE5a,		PTE17,					SPI0_SCK,				UART2_RX,				TPM_CLKIN1,				LPTMR0_ALT3,			FXIO0_D1,				NULL}, 
  { PTE18, 	0, 		ADC0_DP2_ADC0_SE2,		PTE18,					SPI0_MOSI,				NULL,					I2C0_SDA,				SPI0_MISO,				FXIO0_D2,				NULL}, 
  { VREF0, 	0, 		VREF0_B,				NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { NULL,	NULL,	NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL},
  { PTE0,	0,		NULL,					PTE0_CLKOUT32K,			SPI1_MISO,				LPUART1_TX,				RTC_CLKOUT,				CMP0_OUT,				I2C1_SDA,				NULL},
  { PTE1,	0,		NULL,					PTE1,					SPI1_MOSI,				LPUART1_RX,				NULL,					SPI1_MISO,				I2C1_SCL,				NULL},
  { VDD, 	0, 		VDD,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { VSS, 	0, 		VSS,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { USB0_DP,0, 		USB0_DP,				NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { USB0_DM,0, 		USB0_DM,				NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { USB_VDD,0, 		USB_VDD,				NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { PTE16,	0,		ADC0_DP1_ADC0_SE1,		PTE16,					SPI0_PCS0,				UART2_TX,				TPM_CLKIN0,				NULL,					FXIO0_D0,				NULL},
  { PTE20,	0,		ADC0_DP0_ADC0_SE0,		PTE20,					NULL,					TPM1_CH0,				LPUART0_TX,				NULL,					FXIO0_D4,				NULL},
  { PTE21,	0,		ADC0_DM0_ADC0_SE4a,		PTE21,					NULL,					TPM1_CH1,				LPUART0_RX,				NULL,					FXIO0_D5,				NULL},
  { PTE22,	0,		ADC0_DP3_ADC0_SE3,		PTE22,					NULL,					TPM2_CH0,				UART2_TX,				NULL,					FXIO0_D6,				NULL},
  { PTE23,	0,		ADC0_DM3_ADC0_SE7a,		PTE23,					NULL,					TPM2_CH1,				UART2_RX,				NULL,					FXIO0_D7,				NULL},
  { VDDA, 	0, 		VDDA,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { VREFH, 	0, 		VREFH,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { VREF0, 	0, 		VREF0_A,				NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { VREFL, 	0, 		VREFL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { VSSA, 	0, 		VSSA,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { PTE29,	0,		CMP0_IN5_ADC0_SE4b,		PTE29,					NULL,					TPM0_CH2,				TPM_CLKIN0,				NULL,					NULL,					NULL},
  { PTE30,	0,		ADC0_SE23_CMP0_IN4,		PTE30,					NULL,					TPM0_CH3,				TPM_CLKIN1,				LPUART1_TX,				LPTMR0_ALT1,			NULL},
  { PTE31,	0,		NULL,					PTE31,					NULL,					TPM0_CH4,				NULL,					NULL,					NULL,					NULL},
  // Page 29
  { PTE24,	0,		NULL,					PTE24,					NULL,					TPM0_CH0,				NULL,					I2C0_SCL,				NULL,					NULL},
  { PTE25,	0,		NULL,					PTE25,					NULL,					TPM0_CH1,				NULL,					I2C0_SDA,				NULL,					NULL},

  { PTA0,	7,		NULL,					PTA0,					NULL,					TPM0_CH5,				NULL,					NULL,					NULL,					SWD_CLK},
  { PTA1,	0,		NULL,					PTA1,					LPUART0_RX,				TPM2_CH0,				NULL,					NULL,					NULL,					NULL},
  { PTA2,	0,		NULL,					PTA2,					LPUART0_TX,				TPM2_CH1,				NULL,					NULL,					NULL,					NULL},
  { PTA3,	7,		NULL,					PTA3,					I2C1_SCL,				TPM0_CH0,				NULL,					NULL,					NULL,					SWD_DIO},
  { PTA4,	7,		NULL,					PTA4,					I2C1_SDA,				TPM0_CH1,				NULL,					NULL,					NULL,					NMI_b},
  { PTA5,	0,		NULL,					PTA5,					USB_CLKIN,				TPM0_CH2,				NULL,					NULL,					NULL,					NULL},
  { PTA12,	0,		NULL,					PTA12,					NULL,					TPM1_CH0,				NULL,					NULL,					NULL,					NULL},
  { PTA13,	0,		NULL,					PTA13,					NULL,					TPM1_CH1,				NULL,					NULL,					NULL,					NULL},
  { VDD, 	0, 		VDD,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { VSS, 	0, 		VSS,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { PTA18,	0,		EXTAL0,					PTA18,					NULL,					LPUART1_RX,				TPM_CLKIN0,				NULL,					NULL,					NULL},
  { PTA19,	0,		XTAL0,					PTA19,					NULL,					LPUART1_TX,				TPM_CLKIN1,				NULL,					LPTMR0_ALT1,			NULL},
  { PTA20,	7,		NULL,					PTA20,					NULL,					NULL,					NULL,					NULL,					NULL,					RESET_b},
  { PTB0,	0,		ADC0_SE8,				PTB0_LLWU_P5,			I2C0_SCL,				TPM1_CH0,				SPI1_MOSI,				SPI1_MISO,				NULL,					NULL},
  { PTB1,	0,		ADC0_SE9,				PTB1,					I2C0_SDA,				TPM1_CH1,				SPI1_MISO,				SPI1_MOSI,				NULL,					NULL},
  { PTB2,	0,		ADC0_SE12,				PTB2,					I2C0_SCL,				TPM2_CH0,				NULL,					NULL,					NULL,					NULL},
  { PTB3,	0,		ADC0_SE13,				PTB3,					I2C0_SDA,				TPM2_CH1,				NULL,					NULL,					NULL,					NULL},
  { PTB16,	0,		NULL,					PTB16,					SPI1_MOSI,				LPUART0_RX,				TPM_CLKIN0,				SPI1_MISO,				NULL,					NULL},
  { PTB17,	0,		NULL,					PTB17,					SPI1_MISO,				LPUART0_TX,				TPM_CLKIN1,				SPI1_MOSI,				NULL,					NULL},
  { PTB18,	0,		NULL,					PTB18,					NULL,					TPM2_CH0,				NULL,					NULL,					NULL,					NULL},
  { PTB19,	0,		NULL,					PTB19,					NULL,					TPM2_CH1,				NULL,					NULL,					NULL,					NULL},

  { PTC0,	0,		ADC0_SE14,				PTC0,					NULL,					EXTRG_IN,				audioUSB_SOF_OUT,		CMP0_OUT,				NULL,					NULL},
  { PTC1,	0,		ADC0_SE15,				PTC1_LLWU_P6_RTC_CLKIN,	I2C1_SCL,				NULL,					TPM0_CH0,				NULL,					NULL,					NULL},
  { PTC2,	0,		ADC0_SE11,				PTC2,					I2C1_SDA,				NULL,					TPM0_CH1,				NULL,					NULL,					NULL},
  { PTC3,	0,		NULL,					PTC3_LLWU_P7,			SPI1_SCK,				LPUART1_RX,				TPM0_CH2,				CLKOUT,					NULL,					NULL},
  { VSS, 	0, 		VSS,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { VDD, 	0, 		VDD,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}, 
  { PTC4,	0,		NULL,					PTC4_LLWU_P8,			SPI0_PCS0,				LPUART1_TX,				TPM0_CH3,				SPI1_PCS0,				NULL,					NULL},
  // Page 30
  { PTC5,	0,		NULL,					PTC5_LLWU_P9,			SPI0_SCK,				LPTMR0_ALT2,			NULL,					NULL,					CMP0_OUT,				NULL},
  { PTC6,	0,		CMP0_IN0,				PTC6_LLWU_P10,			SPI0_MOSI,				EXTRG_IN,				NULL,					SPI0_MISO,				NULL,					NULL},
  { PTC7,	0,		CMP0_IN1,				PTC7,					SPI0_MISO,				audioUSB_SOF_OUT,		NULL,					SPI0_MOSI,				NULL,					NULL},
  { PTC8,	0,		CMP0_IN2,				PTC8,					I2C0_SCL,				TPM0_CH4,				NULL,					NULL,					NULL,					NULL},
  { PTC9,	0,		CMP0_IN3,				PTC9,					I2C0_SDA,				TPM0_CH5,				NULL,					NULL,					NULL,					NULL},
  { PTC10,	0,		NULL,					PTC10,					I2C1_SCL,				NULL,					NULL,					NULL,					NULL,					NULL},
  { PTC11,	0,		NULL,					PTC11,					I2C1_SDA,				NULL,					NULL,					NULL,					NULL,					NULL},
  
  { PTD0,	0,		NULL,					PTD0,					SPI0_PCS0,				NULL,					TPM0_CH0,				NULL,					FXIO0_D0,				NULL},
  { PTD1,	0,		ADC0_SE5b,				PTD1,					SPI0_SCK,				NULL,					TPM0_CH1,				NULL,					FXIO0_D1,				NULL},
  { PTD2,	0,		NULL,					PTD2,					SPI0_MOSI,				UART2_RX,				TPM0_CH2,				SPI0_MISO,				FXIO0_D2,				NULL},
  { PTD3,	0,		NULL,					PTD3,					SPI0_MISO,				UART2_TX,				TPM0_CH3,				SPI0_MOSI,				FXIO0_D3,				NULL},
  { PTD4,	0,		NULL,					PTD4_LLWU_P14,			SPI1_PCS0,				UART2_RX,				TPM0_CH4,				NULL,					FXIO0_D4,				NULL},
  { PTD5,	0,		ADC0_SE6b,				PTD5,					SPI1_SCK,				UART2_TX,				TPM0_CH5,				NULL,					FXIO0_D5,				NULL},
  { PTD6,	0,		ADC0_SE7b,				PTD6_LLWU_P15,			SPI1_MOSI,				LPUART0_RX,				I2C1_SDA,				SPI1_MISO,				FXIO0_D6,				NULL},
  { PTD7,	0,		NULL,					PTD7,					SPI1_MISO,				LPUART0_TX,				I2C1_SCL,				SPI1_MOSI,				FXIO0_D7,				NULL},

  // Null Filling
  { NULL,	NULL,	NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL,					NULL}
} ;
*/

/*
typedef enum Pin_Names{
	PTE17=0,
	PTE18,
	VREF0,
	NULL,
	PTE0,
	PTE1,
	VDD,
	VSS,
	USB0_DP,
	USB0_DM,
	USB_VDD,
	PTE16,
	PTE20,
	PTE21,
	PTE22,
	PTE23,
	VDDA,
	VREFH,
	VREF01,
	VREFL,
	VSSA,
	PTE29,
	PTE30,
	PTE31,
	PTE24,
	PTE25,
	PTA0,
	PTA1,
	PTA2,
	PTA3,
	PTA4,
	PTA5,
	PTA12,
	PTA13,
	VDD1,
	VSS1,
	PTA18,
	PTA19,
	PTA20,
	PTB0,
	PTB1,
	PTB2,
	PTB3,
	PTB16,
	PTB17,
	PTB18,
	PTB19,
	PTC0,
	PTC1,
	PTC2,
	PTC3,
	VSS2,
	VDD2,
	PTC4,
	PTC5,
	PTC6,
	PTC7,
	PTC8,
	PTC9,
	PTC10,
	PTC11,
	PTD0,
	PTD1,
	PTD2,
	PTD3,
	PTD4,
	PTD5,
	PTD6,
	PTD7
}

typedef enum Mux_Values{
	ADC0_DM0_ADC0_SE4a,
	ADC0_DM1_ADC0_SE5a,
	ADC0_DM3_ADC0_SE7a,
	ADC0_DP0_ADC0_SE0,
	ADC0_DP1_ADC0_SE1,
	ADC0_DP2_ADC0_SE2,
	ADC0_DP3_ADC0_SE3,
	ADC0_SE11,
	ADC0_SE12,
	ADC0_SE13,
	ADC0_SE14,
	ADC0_SE15,
	ADC0_SE23_CMP0_IN4,
	ADC0_SE5b,
	ADC0_SE6b,
	ADC0_SE7b,
	ADC0_SE8,
	ADC0_SE9,
	audioUSB_SOF_OUT,
	CLKOUT,
	CMP0_IN0,
	CMP0_IN1,
	CMP0_IN2,
	CMP0_IN3,
	CMP0_IN5_ADC0_SE4b,
	CMP0_OUT,
	EXTAL0,
	EXTRG_IN,
	FXIO0_D0,
	FXIO0_D1,
	FXIO0_D2,
	FXIO0_D3,
	FXIO0_D4,
	FXIO0_D5,
	FXIO0_D6,
	FXIO0_D7,
	I2C0_SCL,
	I2C0_SDA,
	I2C1_SCL,
	I2C1_SDA,
	LPTMR0_ALT1,
	LPTMR0_ALT2,
	LPTMR0_ALT3,
	LPUART0_RX,
	LPUART0_TX,
	LPUART1_RX,
	LPUART1_TX,
	NMI_b,
	NULL,
	PTA0,
	PTA1,
	PTA12,
	PTA13,
	PTA18,
	PTA19,
	PTA2,
	PTA20,
	PTA3,
	PTA4,
	PTA5,
	PTB0_LLWU_P5,
	PTB1,
	PTB16,
	PTB17,
	PTB18,
	PTB19,
	PTB2,
	PTB3,
	PTC0,
	PTC1_LLWU_P6_RTC_CLKIN,
	PTC10,
	PTC11,
	PTC2,
	PTC3_LLWU_P7,
	PTC4_LLWU_P8,
	PTC5_LLWU_P9,
	PTC6_LLWU_P10,
	PTC7,
	PTC8,
	PTC9,
	PTD0,
	PTD1,
	PTD2,
	PTD3,
	PTD4_LLWU_P14,
	PTD5,
	PTD6_LLWU_P15,
	PTD7,
	PTE0_CLKOUT32K,
	PTE1,
	PTE16,
	PTE17,
	PTE18,
	PTE20,
	PTE21,
	PTE22,
	PTE23,
	PTE24,
	PTE25,
	PTE29,
	PTE30,
	PTE31,
	RESET_b,
	RTC_CLKOUT,
	SPI0_MISO,
	SPI0_MOSI,
	SPI0_PCS0,
	SPI0_SCK,
	SPI1_MISO,
	SPI1_MOSI,
	SPI1_PCS0,
	SPI1_SCK,
	SWD_CLK,
	SWD_DIO,
	TPM_CLKIN0,
	TPM_CLKIN1,
	TPM0_CH0,
	TPM0_CH1,
	TPM0_CH2,
	TPM0_CH3,
	TPM0_CH4,
	TPM0_CH5,
	TPM1_CH0,
	TPM1_CH1,
	TPM2_CH0,
	TPM2_CH1,
	UART2_RX,
	UART2_TX,
	USB_CLKIN,
	USB_VDD,
	USB0_DM,
	USB0_DP,
	VDD,
	VDDA,
	VREF0_A,
	VREF0_B,
	VREFH,
	VREFL,
	VSS,
	VSSA,
	XTAL0
}
*/
